# Learn more: 
# https://docs.gitlab.com/ee/ci/yaml/README.html#script
# https://docs.platformio.org/en/latest/integration/ci/gitlab.html
# After committing this template, visit CI/CD > Jobs to see the script output.

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_UPDATE_STRATEGY: default
  PLATFORMIO_CI_SRC: src/main.c
  DOCUSAURUS_PAGE_DIR: $CI_PROJECT_DIR
  DOCUSAURUS_BUILD_DIR: $DOCUSAURUS_PAGE_DIR/build
  DOCUSAURUS_GITLAB_PAGES_ARTIFACT_DIR: $CI_PROJECT_DIR/public
  NODE_DOCKER_VERSION: '16-alpine'

image: node:$NODE_DOCKER_VERSION

before_script:
  - 'echo "----------- Variables ---------------"'
  - 'echo "CI_JOB_STAGE: $CI_JOB_STAGE"'
  - 'echo "CI_COMMIT_REF_NAME: $CI_COMMIT_REF_NAME"'
  - 'echo "PWD: $PWD"'
  - 'echo "Node: $(node --version)"'
  - 'echo "NPM: $(npm --version)"'
  - 'echo'

build:
  stage: build
  allow_failure: false
  interruptible: true
  script:
    - npm install
    - npm run build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

pages:
  stage: deploy
  allow_failure: false
  interruptible: false
  script:
    - cd $DOCUSAURUS_PAGE_DIR
    - 'echo "---------- PWD: $PWD"'
    - npm install
    - npm run build
    - cd -
    - 'echo "---------- PWD: $PWD"'
    - mv $DOCUSAURUS_BUILD_DIR $DOCUSAURUS_GITLAB_PAGES_ARTIFACT_DIR
    - echo '-----------------------------------'
    - echo "$CI_PAGES_URL    "
    - echo "-----------------------------------"
    
  artifacts:
    paths:
      - $DOCUSAURUS_GITLAB_PAGES_ARTIFACT_DIR
  only:
      - main
